# - Find GSL
FIND_PATH(GSL_INCLUDE_DIR gsl/gsl_interp.h
    PATHS ${SYSTEM_INC_PATH}
    PATHS $ENV{INCLUDE})

FIND_LIBRARY(GSL_LIBRARY gsl
    PATHS ${SYSTEM_LIB_PATH}
    PATHS $ENV{LD_LIBRARY_PATH})

IF (GSL_INCLUDE_DIR AND GSL_LIBRARY)
    IF (NOT GSL_FIND_QUIETLY)
        MESSAGE(STATUS "Found GSL: ${GSL_LIBRARY}")
    ENDIF (NOT GSL_FIND_QUIETLY)
ELSE (GSL_INCLUDE_DIR AND GSL_LIBRARY)
    IF (GSL_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Could not find GSL")
    ENDIF (GSL_FIND_REQUIRED)
ENDIF (GSL_INCLUDE_DIR AND GSL_LIBRARY)
